language: java
sudo: false

matrix:
  fast_finish: true
  include:
    # checkstyle
    - jdk: oraclejdk8
      env:
        - DESC="checkstyle"
        - CMD="mvn clean checkstyle:checkstyle -Dcheckstyle.skip=false"
    # unit tests (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="oraclejdk8 unit tests"
        - CMD="mvn clean verify -DskipITs=true"
